<script setup lang="ts">
import { onMounted, ref } from "vue";
import { api, json } from "../api";
import FnButton from "../components/FnButton.vue";
import FnCard from "../components/FnCard.vue";
import FnDialog from "../components/FnDialog.vue";
import FnEmpty from "../components/FnEmpty.vue";
import FnFormItem from "../components/FnFormItem.vue";
import FnInput from "../components/FnInput.vue";
import FnPageHeader from "../components/FnPageHeader.vue";
import FnSelect from "../components/FnSelect.vue";
import FnSwitch from "../components/FnSwitch.vue";
import FnTable from "../components/FnTable.vue";
import FnTag from "../components/FnTag.vue";
const client=ref<any>(), versions=ref<any[]>([]), sources=ref<any[]>([]), message=ref(""), version=ref(""), sourceID=ref(""), uploadOpen=ref(false), sourceOpen=ref(false), allowUnverified=ref(false), file=ref<HTMLInputElement>();
const source=ref({name:"",enabled:true,priority:10,urlTemplate:"",timeoutSeconds:60});
async function refresh(){try{[client.value,versions.value,sources.value]=await Promise.all([api<any>("/api/client"),api<any[]>("/api/client/versions"),api<any[]>("/api/download-sources")]);message.value=""}catch{message.value="无法读取客户端管理状态。"}}
async function action(path:string,body?:object){if(!confirm("确认执行此操作？"))return;try{await api(path,json(body||{}));await refresh();message.value="操作已完成。"}catch{message.value="操作失败。"}}
async function checkUpdate(){try{const release:any=await api("/api/client/check-update",json({version:""}));version.value=release.version;message.value=`发现官方版本 ${release.version}。`}catch{message.value="无法查询官方版本。"}}
async function download(){try{await api("/api/client/download",json({version:version.value,sourceId:sourceID.value}));message.value="已完成官方 checksum 校验并安装。";await refresh()}catch{message.value="下载或 checksum 校验失败。"}}
async function upload(){const selected=file.value?.files?.[0];if(!selected)return;try{const body=new FormData();body.append("file",selected);body.append("allowUnverified",String(allowUnverified.value));await api("/api/client/upload",{method:"POST",body});uploadOpen.value=false;message.value="上传已验证并安装。";await refresh()}catch{message.value="上传被拒绝。未验证文件需要明确高级确认。"}}
async function saveSource(){try{await api("/api/download-sources",json(source.value));sourceOpen.value=false;source.value={name:"",enabled:true,priority:10,urlTemplate:"",timeoutSeconds:60};await refresh()}catch{message.value="下载源配置无效。"}}
async function removeVersion(item:any){if(!confirm(`删除历史版本 ${item.version}？`))return;try{await api(`/api/client/versions/${encodeURIComponent(item.version)}`,{method:"DELETE"});await refresh()}catch{message.value="不能删除当前或受保护的版本。"}}
async function removeSource(id:string){if(!confirm("删除下载源？"))return;try{await api(`/api/download-sources/${encodeURIComponent(id)}`,{method:"DELETE"});await refresh()}catch{message.value="删除下载源失败。"}}
async function testSource(id:string){try{await api(`/api/download-sources/${encodeURIComponent(id)}/test`,json({}));message.value="下载源连通。"}catch{message.value="下载源测试失败。"}}
onMounted(()=>void refresh());
</script>
<template>
  <FnPageHeader title="客户端管理" description="客户端版本与下载源"><template #default><FnButton @click="refresh">刷新</FnButton><FnButton @click="checkUpdate">检查更新</FnButton><FnButton variant="primary" @click="uploadOpen=true">上传版本</FnButton></template></FnPageHeader>
  <p v-if="message" class="message">{{message}}</p>
  <FnCard v-if="client" class="client-hero"><div><p class="eyebrow">当前客户端</p><h2>{{client.version||"不可用"}} <FnTag :type="client.source==='managed'?'primary':'success'">{{client.source==='managed'?'在线安装':'内置版本'}}</FnTag></h2><p>{{client.arch||"—"}} · {{client.checksum||"未提供 checksum"}}</p></div><div class="hero-actions"><FnButton @click="action('/api/client/rollback')">回滚上一版本</FnButton><FnButton variant="primary" @click="action('/api/client/use-bundled')">回退内置版本</FnButton></div></FnCard>
  <div class="layout"><FnCard><h3>已安装版本</h3><p class="fn-note">当前版本无法删除。</p><FnTable v-if="versions.length"><thead><tr><th>版本</th><th>架构</th><th>来源</th><th></th></tr></thead><tbody><tr v-for="item in versions" :key="item.version"><td><strong>{{item.version}}</strong></td><td>{{item.arch}}</td><td><FnTag :type="item.source==='bundled'?'success':'primary'">{{item.source}}</FnTag></td><td class="actions"><FnButton @click="action('/api/client/switch',{version:item.version})">切换</FnButton><FnButton variant="danger" @click="removeVersion(item)">删除</FnButton></td></tr></tbody></FnTable><FnEmpty v-else>没有已安装的受管版本</FnEmpty></FnCard>
    <FnCard><h3>在线安装</h3><p class="fn-note">使用官方 checksum 校验。</p><div class="download-form"><FnFormItem label="目标版本"><FnInput v-model="version" placeholder="例如：0.75.0"/></FnFormItem><FnFormItem label="下载源"><FnSelect v-model="sourceID"><option value="">官方源</option><option v-for="item in sources.filter(item=>item.enabled)" :key="item.id" :value="item.id">{{item.name}}</option></FnSelect></FnFormItem><FnButton variant="primary" :disabled="!version" @click="download">下载并安装</FnButton></div></FnCard></div>
  <FnCard class="sources"><header><div><h3>下载源</h3><p class="fn-note">{url} 为完整官方 URL。</p></div><FnButton @click="sourceOpen=true">添加下载源</FnButton></header><FnTable v-if="sources.length"><thead><tr><th>名称</th><th>优先级</th><th>状态</th><th>操作</th></tr></thead><tbody><tr v-for="item in sources" :key="item.id"><td><strong>{{item.name}}</strong><small>{{item.urlTemplate}}</small></td><td>{{item.priority}}</td><td><FnTag :type="item.enabled?'success':'muted'">{{item.enabled?'启用':'停用'}}</FnTag></td><td class="actions"><FnButton @click="testSource(item.id)">测试</FnButton><FnButton variant="danger" @click="removeSource(item.id)">删除</FnButton></td></tr></tbody></FnTable><FnEmpty v-else>未配置第三方下载源</FnEmpty></FnCard>
  <FnDialog :open="uploadOpen" title="上传 NetBird 客户端" @close="uploadOpen=false"><div class="dialog-form"><p class="fn-note">仅接受 netbird ELF 或 tar.gz；上传会进行校验。</p><FnFormItem label="文件"><input ref="file" class="file" type="file" accept="application/gzip,.gz,application/octet-stream"/></FnFormItem><div class="unverified"><div><strong>允许未通过官方来源校验</strong><p>仅限高级用户；来源将记录为 upload-unverified。</p></div><FnSwitch v-model="allowUnverified"/></div></div><template #footer><FnButton @click="uploadOpen=false">取消</FnButton><FnButton variant="primary" @click="upload">验证并安装</FnButton></template></FnDialog>
  <FnDialog :open="sourceOpen" title="添加下载源" @close="sourceOpen=false"><div class="dialog-form"><FnFormItem label="名称"><FnInput v-model="source.name" placeholder="例如：公司镜像"/></FnFormItem><FnFormItem label="URL 模板" hint="必须使用 HTTPS，且包含一个 {url}"><FnInput v-model="source.urlTemplate" placeholder="https://proxy.example/{url}"/></FnFormItem><FnFormItem label="优先级"><FnInput :model-value="String(source.priority)" type="number" @update:model-value="source.priority=Number($event)"/></FnFormItem><div class="unverified"><span>启用下载源</span><FnSwitch v-model="source.enabled"/></div></div><template #footer><FnButton @click="sourceOpen=false">取消</FnButton><FnButton variant="primary" @click="saveSource">保存</FnButton></template></FnDialog>
</template>
<style scoped>.client-hero{display:flex;justify-content:space-between;align-items:center;gap:20px;background:linear-gradient(115deg,#f8fbff,#fff)}.eyebrow{margin:0;color:var(--fn-muted);font-size:13px}.client-hero h2{margin:5px 0;font-size:23px}.client-hero h2 :deep(.tag){vertical-align:middle;font-size:12px}.client-hero p:not(.eyebrow){margin:0;color:var(--fn-muted);font-size:13px;word-break:break-all}.hero-actions,.actions{display:flex;gap:8px}.layout{display:grid;grid-template-columns:1.25fr .75fr;gap:16px;margin-top:16px}.layout h3,.sources h3{margin:0 0 8px;font-size:17px}.download-form{display:grid;gap:14px;margin-top:18px}.sources{margin-top:16px}.sources>header{display:flex;justify-content:space-between;gap:16px;align-items:start;margin-bottom:15px}.sources small{display:block;color:var(--fn-muted);max-width:340px;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.message{padding:10px 12px;border:1px solid #cfe4ff;border-radius:10px;background:#f3f8ff;color:#2569b5;font-size:13px}.dialog-form{display:grid;gap:14px}.file{width:100%;height:var(--fn-control);padding:7px;border:1px dashed var(--fn-border);border-radius:9px;background:#fafbfd}.unverified{display:flex;justify-content:space-between;gap:16px;align-items:center}.unverified p{margin:5px 0 0;color:var(--fn-muted);font-size:13px}@media(max-width:820px){.client-hero,.sources>header{align-items:flex-start;flex-direction:column}.layout{grid-template-columns:1fr}.actions{flex-wrap:wrap}}</style>
