<script setup lang="ts">
import { computed, onBeforeUnmount, onMounted, ref } from "vue";
import { api } from "../api"; import FnButton from "../components/FnButton.vue"; import FnCard from "../components/FnCard.vue"; import FnEmpty from "../components/FnEmpty.vue"; import FnInput from "../components/FnInput.vue"; import FnPageHeader from "../components/FnPageHeader.vue"; import FnSelect from "../components/FnSelect.vue"; import FnTable from "../components/FnTable.vue"; import FnTag from "../components/FnTag.vue";
const peers=ref<any[]>([]), query=ref(""), mode=ref("all"), expanded=ref(""); const error=ref(""); let timer:number|undefined;
const shown=computed(()=>peers.value.filter(p=>{const q=query.value.toLowerCase(); return (!q || [p.name,p.ip,p.id].join(" ").toLowerCase().includes(q)) && (mode.value==="all" || mode.value==="online"&&p.connected || mode.value==="direct"&&p.direct || mode.value==="relay"&&p.connected&&!p.direct)}));
async function load(){try{peers.value=await api("/api/peers");error.value=""}catch{error.value="无法读取 Peer 连接状态。"}}
onMounted(()=>{load();timer=window.setInterval(load,15000)});onBeforeUnmount(()=>{if(timer)window.clearInterval(timer)});
</script>
<template><FnPageHeader title="Peers" description="每 15 秒从官方 NetBird CLI 刷新一次"><template #default><FnButton @click="load">刷新</FnButton></template></FnPageHeader><FnCard><div class="filters"><FnInput v-model="query" placeholder="搜索名称、IP 或 ID"/><FnSelect v-model="mode"><option value="all">全部</option><option value="online">在线</option><option value="direct">Direct</option><option value="relay">Relay</option></FnSelect></div><p v-if="error" class="error">{{error}}</p><FnTable v-if="shown.length"><thead><tr><th>Peer</th><th>IP</th><th>状态</th><th>链路</th><th>延迟</th></tr></thead><tbody><template v-for="peer in shown" :key="peer.id"><tr @click="expanded=expanded===peer.id?'':peer.id"><td><strong>{{peer.name||peer.id}}</strong><small>{{peer.id}}</small></td><td>{{peer.ip||'—'}}</td><td><FnTag :type="peer.connected?'success':'muted'">{{peer.connected?'在线':'离线'}}</FnTag></td><td>{{peer.direct?'Direct':'Relay'}}</td><td>{{peer.latencyMs ? peer.latencyMs+' ms':'—'}}</td></tr><tr v-if="expanded===peer.id" class="detail"><td colspan="5"><span>Endpoint {{peer.endpoint||'—'}}</span><span>OS {{peer.os||'—'}}</span><span>Version {{peer.version||'—'}}</span><span>最近连接 {{peer.lastSeen||'—'}}</span></td></tr></template></tbody></FnTable><FnEmpty v-else>当前没有符合条件的 Peer</FnEmpty></FnCard></template>
<style scoped>.filters{display:flex;gap:10px;margin-bottom:16px}.filters :first-child{flex:1}.filters :last-child{width:130px}td{cursor:pointer}td small{display:block;color:var(--fn-muted);margin-top:3px}.detail td{cursor:default;background:#f8fafc}.detail span{display:inline-block;margin-right:24px;color:var(--fn-muted);font-size:13px}.error{color:#c43226}</style>
